version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: calmis_pg
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hospital_lab_db

    ports:
      - "5555:5432"

    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFUALT_PASSWORD:
      PGADMIN_DB:

    restart: always

    port:
      - "6969:80"

    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin: